// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_collage_project.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_collage_project_proto protoreflect.FileDescriptor

const file_service_collage_project_proto_rawDesc = "" +
	"\n" +
	"\x1dservice_collage_project.proto\x12\x02pb\x1a\n" +
	"user.proto\x1a\rproduct.proto\x1a\vorder.proto\x1a\n" +
	"cart.proto\x1a\x1cgoogle/api/annotations.proto2\xc6\x15\n" +
	"\x0eCollageProject\x12M\n" +
	"\n" +
	"SignUpUser\x12\x11.pb.SignUpRequest\x1a\x10.pb.AuthResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/api/sign-in\x12I\n" +
	"\tLoginUser\x12\x10.pb.LoginRequest\x1a\x10.pb.AuthResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/api/login\x12N\n" +
	"\vGetUserByID\x12\x12.pb.GetUserRequest\x1a\x10.pb.UserResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/api/userId\x12[\n" +
	"\x0eGetUserByEmail\x12\x19.pb.GetUserByEmailRequest\x1a\x10.pb.UserResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/api/UserEmail\x12T\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x10.pb.UserResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/api/updateUser\x12Z\n" +
	"\n" +
	"DeleteUser\x12\x15.pb.DeleteUserRequest\x1a\x16.pb.DeleteUserResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/api/deleteUser\x12b\n" +
	"\fRefreshToken\x12\x17.pb.RefreshTokenRequest\x1a\x18.pb.RefreshTokenResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/api/refreshToken\x12`\n" +
	"\rCreateProduct\x12\x18.pb.CreateProductRequest\x1a\x13.pb.ProductResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/api/createProduct\x12Z\n" +
	"\x0eGetProductByID\x12\x15.pb.GetProductRequest\x1a\x13.pb.ProductResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/api/productId\x12e\n" +
	"\x15GetOnlyProductRequest\x12\x15.pb.GetProductRequest\x1a\x13.pb.ProductResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/api/productOnlyId\x12x\n" +
	"\x12GetProductByUserID\x12\x1d.pb.ListAllProductsByCreateBy\x1a!.pb.ListAllProductsByNameResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/api/productByUser\x12d\n" +
	"\fListProducts\x12\x1a.pb.ListAllProductsRequest\x1a\x18.pb.ListProductsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/api/listProduct\x12`\n" +
	"\rUpdateProduct\x12\x18.pb.UpdateProductRequest\x1a\x13.pb.ProductResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/api/updateProduct\x12f\n" +
	"\rDeleteProduct\x12\x18.pb.DeleteProductRequest\x1a\x19.pb.DeleteProductResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/api/deleteProduct\x12|\n" +
	"\x12ListProductsByName\x12 .pb.ListAllProductsByNameRequest\x1a!.pb.ListAllProductsByNameResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/api/getProductName\x12\x8c\x01\n" +
	"\x16ListProductsByCategory\x12$.pb.ListAllProductsByCategoryRequest\x1a%.pb.ListAllProductsByCategoryResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/api/getProductCategory\x12\x80\x01\n" +
	"\x12ListProductsByType\x12 .pb.ListAllProductsByTypeRequest\x1a%.pb.ListAllProductsByCategoryResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/api/getProductType\x12^\n" +
	"\x0eSearchProducts\x12\x19.pb.SearchProductsRequest\x1a\x1a.pb.SearchProductsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/search\x12X\n" +
	"\vCreateOrder\x12\x16.pb.CreateOrderRequest\x1a\x11.pb.OrderResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/api/createOrder\x12R\n" +
	"\fGetOrderByID\x12\x13.pb.GetOrderRequest\x1a\x11.pb.OrderResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/api/orderId\x12_\n" +
	"\n" +
	"ListOrders\x12\x1b.pb.ListOrdersByUserRequest\x1a\x16.pb.ListOrdersResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/api/orderList\x12d\n" +
	"\x11UpdateOrderStatus\x12\x1c.pb.UpdateOrderStatusRequest\x1a\x11.pb.OrderResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/api/udateOreder\x12^\n" +
	"\vDeleteOrder\x12\x16.pb.DeleteOrderRequest\x1a\x17.pb.DeleteOrderResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/api/deleteOrder\x12R\n" +
	"\tAddToCart\x12\x14.pb.AddToCartRequest\x1a\x10.pb.CartResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/api/createCart\x12V\n" +
	"\rGetCartByUser\x12\x12.pb.GetCartRequest\x1a\x14.pb.CartListResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/api/userCart\x12f\n" +
	"\x12UpdateCartQuantity\x12\x1d.pb.UpdateCartQuantityRequest\x1a\x10.pb.CartResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/api/cartQuantity\x12\\\n" +
	"\x0eRemoveFromCart\x12\x19.pb.RemoveFromCartRequest\x1a\x10.pb.CartResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/api/removeCart\x12Q\n" +
	"\tClearCart\x12\x14.pb.ClearCartRequest\x1a\x10.pb.CartResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/api/clearCartB@Z>github.com/siddheshRajendraNimbalkar/collage-prject-backend/pbb\x06proto3"

var file_service_collage_project_proto_goTypes = []any{
	(*SignUpRequest)(nil),                     // 0: pb.SignUpRequest
	(*LoginRequest)(nil),                      // 1: pb.LoginRequest
	(*GetUserRequest)(nil),                    // 2: pb.GetUserRequest
	(*GetUserByEmailRequest)(nil),             // 3: pb.GetUserByEmailRequest
	(*UpdateUserRequest)(nil),                 // 4: pb.UpdateUserRequest
	(*DeleteUserRequest)(nil),                 // 5: pb.DeleteUserRequest
	(*RefreshTokenRequest)(nil),               // 6: pb.RefreshTokenRequest
	(*CreateProductRequest)(nil),              // 7: pb.CreateProductRequest
	(*GetProductRequest)(nil),                 // 8: pb.GetProductRequest
	(*ListAllProductsByCreateBy)(nil),         // 9: pb.ListAllProductsByCreateBy
	(*ListAllProductsRequest)(nil),            // 10: pb.ListAllProductsRequest
	(*UpdateProductRequest)(nil),              // 11: pb.UpdateProductRequest
	(*DeleteProductRequest)(nil),              // 12: pb.DeleteProductRequest
	(*ListAllProductsByNameRequest)(nil),      // 13: pb.ListAllProductsByNameRequest
	(*ListAllProductsByCategoryRequest)(nil),  // 14: pb.ListAllProductsByCategoryRequest
	(*ListAllProductsByTypeRequest)(nil),      // 15: pb.ListAllProductsByTypeRequest
	(*SearchProductsRequest)(nil),             // 16: pb.SearchProductsRequest
	(*CreateOrderRequest)(nil),                // 17: pb.CreateOrderRequest
	(*GetOrderRequest)(nil),                   // 18: pb.GetOrderRequest
	(*ListOrdersByUserRequest)(nil),           // 19: pb.ListOrdersByUserRequest
	(*UpdateOrderStatusRequest)(nil),          // 20: pb.UpdateOrderStatusRequest
	(*DeleteOrderRequest)(nil),                // 21: pb.DeleteOrderRequest
	(*AddToCartRequest)(nil),                  // 22: pb.AddToCartRequest
	(*GetCartRequest)(nil),                    // 23: pb.GetCartRequest
	(*UpdateCartQuantityRequest)(nil),         // 24: pb.UpdateCartQuantityRequest
	(*RemoveFromCartRequest)(nil),             // 25: pb.RemoveFromCartRequest
	(*ClearCartRequest)(nil),                  // 26: pb.ClearCartRequest
	(*AuthResponse)(nil),                      // 27: pb.AuthResponse
	(*UserResponse)(nil),                      // 28: pb.UserResponse
	(*DeleteUserResponse)(nil),                // 29: pb.DeleteUserResponse
	(*RefreshTokenResponse)(nil),              // 30: pb.RefreshTokenResponse
	(*ProductResponse)(nil),                   // 31: pb.ProductResponse
	(*ListAllProductsByNameResponse)(nil),     // 32: pb.ListAllProductsByNameResponse
	(*ListProductsResponse)(nil),              // 33: pb.ListProductsResponse
	(*DeleteProductResponse)(nil),             // 34: pb.DeleteProductResponse
	(*ListAllProductsByCategoryResponse)(nil), // 35: pb.ListAllProductsByCategoryResponse
	(*SearchProductsResponse)(nil),            // 36: pb.SearchProductsResponse
	(*OrderResponse)(nil),                     // 37: pb.OrderResponse
	(*ListOrdersResponse)(nil),                // 38: pb.ListOrdersResponse
	(*DeleteOrderResponse)(nil),               // 39: pb.DeleteOrderResponse
	(*CartResponse)(nil),                      // 40: pb.CartResponse
	(*CartListResponse)(nil),                  // 41: pb.CartListResponse
}
var file_service_collage_project_proto_depIdxs = []int32{
	0,  // 0: pb.CollageProject.SignUpUser:input_type -> pb.SignUpRequest
	1,  // 1: pb.CollageProject.LoginUser:input_type -> pb.LoginRequest
	2,  // 2: pb.CollageProject.GetUserByID:input_type -> pb.GetUserRequest
	3,  // 3: pb.CollageProject.GetUserByEmail:input_type -> pb.GetUserByEmailRequest
	4,  // 4: pb.CollageProject.UpdateUser:input_type -> pb.UpdateUserRequest
	5,  // 5: pb.CollageProject.DeleteUser:input_type -> pb.DeleteUserRequest
	6,  // 6: pb.CollageProject.RefreshToken:input_type -> pb.RefreshTokenRequest
	7,  // 7: pb.CollageProject.CreateProduct:input_type -> pb.CreateProductRequest
	8,  // 8: pb.CollageProject.GetProductByID:input_type -> pb.GetProductRequest
	8,  // 9: pb.CollageProject.GetOnlyProductRequest:input_type -> pb.GetProductRequest
	9,  // 10: pb.CollageProject.GetProductByUserID:input_type -> pb.ListAllProductsByCreateBy
	10, // 11: pb.CollageProject.ListProducts:input_type -> pb.ListAllProductsRequest
	11, // 12: pb.CollageProject.UpdateProduct:input_type -> pb.UpdateProductRequest
	12, // 13: pb.CollageProject.DeleteProduct:input_type -> pb.DeleteProductRequest
	13, // 14: pb.CollageProject.ListProductsByName:input_type -> pb.ListAllProductsByNameRequest
	14, // 15: pb.CollageProject.ListProductsByCategory:input_type -> pb.ListAllProductsByCategoryRequest
	15, // 16: pb.CollageProject.ListProductsByType:input_type -> pb.ListAllProductsByTypeRequest
	16, // 17: pb.CollageProject.SearchProducts:input_type -> pb.SearchProductsRequest
	17, // 18: pb.CollageProject.CreateOrder:input_type -> pb.CreateOrderRequest
	18, // 19: pb.CollageProject.GetOrderByID:input_type -> pb.GetOrderRequest
	19, // 20: pb.CollageProject.ListOrders:input_type -> pb.ListOrdersByUserRequest
	20, // 21: pb.CollageProject.UpdateOrderStatus:input_type -> pb.UpdateOrderStatusRequest
	21, // 22: pb.CollageProject.DeleteOrder:input_type -> pb.DeleteOrderRequest
	22, // 23: pb.CollageProject.AddToCart:input_type -> pb.AddToCartRequest
	23, // 24: pb.CollageProject.GetCartByUser:input_type -> pb.GetCartRequest
	24, // 25: pb.CollageProject.UpdateCartQuantity:input_type -> pb.UpdateCartQuantityRequest
	25, // 26: pb.CollageProject.RemoveFromCart:input_type -> pb.RemoveFromCartRequest
	26, // 27: pb.CollageProject.ClearCart:input_type -> pb.ClearCartRequest
	27, // 28: pb.CollageProject.SignUpUser:output_type -> pb.AuthResponse
	27, // 29: pb.CollageProject.LoginUser:output_type -> pb.AuthResponse
	28, // 30: pb.CollageProject.GetUserByID:output_type -> pb.UserResponse
	28, // 31: pb.CollageProject.GetUserByEmail:output_type -> pb.UserResponse
	28, // 32: pb.CollageProject.UpdateUser:output_type -> pb.UserResponse
	29, // 33: pb.CollageProject.DeleteUser:output_type -> pb.DeleteUserResponse
	30, // 34: pb.CollageProject.RefreshToken:output_type -> pb.RefreshTokenResponse
	31, // 35: pb.CollageProject.CreateProduct:output_type -> pb.ProductResponse
	31, // 36: pb.CollageProject.GetProductByID:output_type -> pb.ProductResponse
	31, // 37: pb.CollageProject.GetOnlyProductRequest:output_type -> pb.ProductResponse
	32, // 38: pb.CollageProject.GetProductByUserID:output_type -> pb.ListAllProductsByNameResponse
	33, // 39: pb.CollageProject.ListProducts:output_type -> pb.ListProductsResponse
	31, // 40: pb.CollageProject.UpdateProduct:output_type -> pb.ProductResponse
	34, // 41: pb.CollageProject.DeleteProduct:output_type -> pb.DeleteProductResponse
	32, // 42: pb.CollageProject.ListProductsByName:output_type -> pb.ListAllProductsByNameResponse
	35, // 43: pb.CollageProject.ListProductsByCategory:output_type -> pb.ListAllProductsByCategoryResponse
	35, // 44: pb.CollageProject.ListProductsByType:output_type -> pb.ListAllProductsByCategoryResponse
	36, // 45: pb.CollageProject.SearchProducts:output_type -> pb.SearchProductsResponse
	37, // 46: pb.CollageProject.CreateOrder:output_type -> pb.OrderResponse
	37, // 47: pb.CollageProject.GetOrderByID:output_type -> pb.OrderResponse
	38, // 48: pb.CollageProject.ListOrders:output_type -> pb.ListOrdersResponse
	37, // 49: pb.CollageProject.UpdateOrderStatus:output_type -> pb.OrderResponse
	39, // 50: pb.CollageProject.DeleteOrder:output_type -> pb.DeleteOrderResponse
	40, // 51: pb.CollageProject.AddToCart:output_type -> pb.CartResponse
	41, // 52: pb.CollageProject.GetCartByUser:output_type -> pb.CartListResponse
	40, // 53: pb.CollageProject.UpdateCartQuantity:output_type -> pb.CartResponse
	40, // 54: pb.CollageProject.RemoveFromCart:output_type -> pb.CartResponse
	40, // 55: pb.CollageProject.ClearCart:output_type -> pb.CartResponse
	28, // [28:56] is the sub-list for method output_type
	0,  // [0:28] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_collage_project_proto_init() }
func file_service_collage_project_proto_init() {
	if File_service_collage_project_proto != nil {
		return
	}
	file_user_proto_init()
	file_product_proto_init()
	file_order_proto_init()
	file_cart_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_collage_project_proto_rawDesc), len(file_service_collage_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_collage_project_proto_goTypes,
		DependencyIndexes: file_service_collage_project_proto_depIdxs,
	}.Build()
	File_service_collage_project_proto = out.File
	file_service_collage_project_proto_goTypes = nil
	file_service_collage_project_proto_depIdxs = nil
}
