// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	UserID    uuid.NullUUID `db:"user_id" json:"user_id"`
	ProductID uuid.NullUUID `db:"product_id" json:"product_id"`
	Quantity  int32         `db:"quantity" json:"quantity"`
	CreatedAt sql.NullTime  `db:"created_at" json:"created_at"`
}

type Order struct {
	ID         uuid.UUID      `db:"id" json:"id"`
	UserID     uuid.NullUUID  `db:"user_id" json:"user_id"`
	ProductID  uuid.NullUUID  `db:"product_id" json:"product_id"`
	Quantity   int32          `db:"quantity" json:"quantity"`
	TotalPrice string         `db:"total_price" json:"total_price"`
	Status     sql.NullString `db:"status" json:"status"`
	CreatedAt  sql.NullTime   `db:"created_at" json:"created_at"`
}

type Product struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	Name        string        `db:"name" json:"name"`
	Description string        `db:"description" json:"description"`
	Price       string        `db:"price" json:"price"`
	Stock       int32         `db:"stock" json:"stock"`
	ProductUrl  string        `db:"product_url" json:"product_url"`
	Category    string        `db:"category" json:"category"`
	Type        string        `db:"type" json:"type"`
	CreatedBy   uuid.NullUUID `db:"created_by" json:"created_by"`
	CreatedAt   sql.NullTime  `db:"created_at" json:"created_at"`
}

type Session struct {
	ID         uuid.UUID     `db:"id" json:"id"`
	UserID     uuid.NullUUID `db:"user_id" json:"user_id"`
	Token      string        `db:"token" json:"token"`
	CreatedAt  sql.NullTime  `db:"created_at" json:"created_at"`
	ExpiresAt  time.Time     `db:"expires_at" json:"expires_at"`
	TokenBlock sql.NullBool  `db:"token_block" json:"token_block"`
}

type User struct {
	ID               uuid.UUID    `db:"id" json:"id"`
	Name             string       `db:"name" json:"name"`
	Email            string       `db:"email" json:"email"`
	PasswordHash     string       `db:"password_hash" json:"password_hash"`
	Role             string       `db:"role" json:"role"`
	OrganizationName string       `db:"organization_name" json:"organization_name"`
	UserImage        string       `db:"user_image" json:"user_image"`
	CreatedAt        sql.NullTime `db:"created_at" json:"created_at"`
}
